package ai.gyango.chatbot.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember

/**
 * User-visible chat chrome keyed by [InferenceSettings.speechInputLocaleTag]. Changing language in
 * settings updates these strings for the next composition; assistant **message text** follows the
 * same preference via [ai.gyango.api.PromptBuilder].
 */
data class ChatDisplayStrings(
    val topBarTitle: String,
    /** Product tagline shown under the title in the chat top bar and entry screens. */
    val topBarCaption: String,
    val emptyVoicePrimaryTitle: String,
    val emptyVoicePrimarySubtitle: String,
    val emptyTextModeTitle: String,
    val emptyTextModeSubtitle: String,
    val loadingModelMessage: String,
    /** Shown inside the assistant bubble while a reply is streaming and no lesson text is visible yet. */
    val assistantJsonStreamingPlaceholder: String,
    /**
     * Rotating one-liners while the model streams but the formatter has nothing to paint yet
     * (GPU spin-up, first tokens, or markers not yet filled).
     */
    val assistantAwaitingStreamHints: List<String>,
    val loadingDeviceModelTitle: String,
    val loadingDeviceModelSubtitle: String,
    val modelLoadFailedTitle: String,
    val modelLoadRetryButton: String,
    val onboardingProgressSavedHint: String,
    val onboardingPadDownloadingHint: String,
    val onboardingPadWaitingHint: String,
    val micMainContentDescription: String,
    val chatToolbarSwitchToTypeLabel: String,
    val chatToolbarSwitchToVoiceLabel: String,
    val chatToolbarClearLabel: String,
    val chatToolbarSettingsLabel: String,
    val chatToolbarFeedbackLabel: String,
    val brainNetworkHeadline: String,
    val brainNetworkSubtext: String,
    val brainNetworkWifiOnly: String,
    val brainNetworkProceedNow: String,
    val brainWaitingWifiHeadline: String,
    val brainWaitingWifiSubtext: String,
    val brainWaitingWifiOptionsTitle: String,
    val brainWaitingWifiContinueDownloadButton: String,
    val brainWaitingWifiResumeLaterButton: String,
    val brainPreparingHeadline: String,
    val brainPreparingSubtext: String,
    val brainMergingDetail: String,
    val brainRetryDownloadButton: String,
    val brainDownloadFailedHeadline: String,
    val onboardingIntroTitle: String,
    val onboardingIntroBody: String,
    val onboardingIntroContinue: String,
    val onboardingWelcomeTitle: String,
    val onboardingWelcomeBody: String,
    val onboardingFirstNameLabel: String,
    val onboardingLastNameLabel: String,
    val onboardingBirthOptionalSection: String,
    val onboardingBirthMonthLabel: String,
    /** Shown as first option in the birth-month dropdown (optional field). */
    val onboardingBirthMonthNotSet: String,
    val onboardingBirthYearLabel: String,
    val onboardingLanguageSection: String,
    val onboardingVoiceSection: String,
    val onboardingReadAloudSection: String,
    val onboardingReadAloudNoLabel: String,
    val onboardingReadAloudYesLabel: String,
    val onboardingContinue: String,
    val ttsSetupTitle: String,
    val ttsSetupBody: String,
    val ttsSetupInstallButton: String,
    val ttsSetupSkipButton: String,
    val onboardingHardwareUnsupportedTitle: String,
    val onboardingHardwareUnsupportedBody: String,
    /** Shown under the main unsupported message: why CPU-only is not offered. */
    val onboardingHardwareUnsupportedPerformanceNote: String,
    val settingsTitle: String,
    val settingsConversationLanguage: String,
    val settingsConversationLanguageHint: String,
    val settingsSpeechPickerTitle: String,
    val settingsApply: String,
    val settingsCancel: String,
    val settingsHubTitle: String,
    val settingsHubProfileTitle: String,
    val settingsHubProfileSubtitle: String,
    val settingsHubChatTitle: String,
    val settingsHubChatSubtitle: String,
    val settingsProfileTitle: String,
    val settingsChatTitle: String,
    val settingsBack: String,
    val settingsClose: String,
    val profileEmailLabel: String,
    val settingsBirthAgeHint: String,
    /** Chat preferences: longer replies vs quicker ones (maps to max decode length). */
    val settingsChatLongAnswersTitle: String,
    val settingsChatLongAnswersHint: String,
    /** Optional extra “thinking” hint for the model (maps to [InferenceSettings.requestModelThoughtInJson]). */
    val settingsChatReasoningTitle: String,
    val settingsChatReasoningHint: String,
    /** Sampling temperature in plain language. */
    val settingsChatCreativityTitle: String,
    val settingsChatCreativityHint: String,
    val settingsChatLowPowerTitle: String,
    val settingsChatLowPowerHint: String,
    val settingsChangeConversationLanguage: String,
    val settingsHubInterestsTitle: String,
    val settingsHubInterestsSubtitle: String,
    val settingsAboutTitle: String,
    /** Format with [java.util.String.format]: %1\$s = versionName, %2\$s = versionCode. */
    val settingsVersionFormat: String,
    val settingsInterestsTitle: String,
    val settingsInterestsEmpty: String,
    val settingsInterestsHint: String,
    val settingsInterestsClearButton: String,
    val settingsInterestsDoneButton: String,
    val settingsInterestsTopicPrefix: String,
    val settingsInterestsQuestionPrefix: String,
    val onboardingHardwareChecklistTitle: String,
    val onboardingHardwareNoAccelCard: String,
    val onboardingHardwareLowRamCard: String,
    val onboardingHardwareLowDiskCard: String,
    val childSafeBanner: String,
)

/** Shown next to assistant bubbles and in localized copy; keep in sync with branding. */
const val CHAT_ASSISTANT_DISPLAY_NAME = "GyanGo"

/** Global product tagline (English) for captions. */
const val CHAT_BRAND_TAGLINE = "Gyan on the Go"

private const val ASSISTANT = CHAT_ASSISTANT_DISPLAY_NAME

/** Localized “pack x of y” line during PAD download (1-based index). */
fun brainPackProgressDetail(localeTag: String, oneBased: Int, total: Int): String = when {
    localeTag.startsWith("te", ignoreCase = true) ->
        "మొత్తం $total లో $oneBased వ భాగం డౌన్‌లోడ్ అవుతోంది"
    localeTag.startsWith("hi", ignoreCase = true) ->
        "भाग $oneBased / $total डाउनलोड हो रहा है"
    else ->
        "Downloading pack $oneBased of $total"
}

fun chatDisplayStringsForLocale(localeTag: String): ChatDisplayStrings {
    return when {
        localeTag.startsWith("te", ignoreCase = true) -> ChatDisplayStrings(
            topBarTitle = CHAT_ASSISTANT_DISPLAY_NAME,
            topBarCaption = CHAT_BRAND_TAGLINE,
            emptyVoicePrimaryTitle = "మీ వాయిస్‌తో ప్రారంభించండి",
            emptyVoicePrimarySubtitle = "మైక్రోఫోన్‌ను నొక్కి సహజంగా మాట్లాడండి — $ASSISTANT ఈ ఫోన్‌లోనే వింటుంది మరియు స్పందిస్తుంది.",
            emptyTextModeTitle = "టెక్స్ట్‌తో ప్రారంభించండి",
            emptyTextModeSubtitle = "సందేశం టైప్ చేయండి, లేదా చిత్రాన్ని జోడించి దానిపై ఉన్న టెక్స్ట్‌ను చేర్చండి (OCR). అవసరమైతే టూల్‌బార్ నుండి వాయిస్‌కు మారండి.",
            loadingModelMessage = "మోడల్ సిద్ధమవుతోంది — ఒక్క క్షణం.",
            assistantJsonStreamingPlaceholder = "ఆలోచిస్తున్నాను…",
            assistantAwaitingStreamHints = listOf(
                "మీ ప్రశ్న ఈ ఫోన్‌లోనే ఉంటుంది — సమాధానాన్ని సిద్ధం చేస్తున్నాను…",
                "క్లౌడ్‌కు వెళ్లకుండానే — ఇక్కడే ఆలోచిస్తున్నాను…",
                "స్పష్టంగా చెప్పడానికి కొన్ని క్షణాలు తీసుకుంటున్నాను…",
                "చదవడానికి సులభంగా అమరుస్తున్నాను…",
                "మొదటి మాటలు దగ్గరలోనే…",
            ),
            loadingDeviceModelTitle = "ఆన్‑డివైస్ AI సిద్ధమవుతోంది",
            loadingDeviceModelSubtitle = "మొదటి ప్రారంభం కొంచెం సమయం తీసుకోవచ్చు. దయచేసి వేచి ఉండండి.",
            modelLoadFailedTitle = "మోడల్ లోడ్ కాలేదు",
            modelLoadRetryButton = "మళ్లీ ప్రయత్నించండి",
            onboardingProgressSavedHint = "ఈ పరికరంలో మీ వివరాలు సేవ్ అవుతాయి.",
            onboardingPadDownloadingHint = "బ్రెయిన్ మోడల్ బ్యాక్‌గ్రౌండ్‌లో డౌన్‌లోడ్ అవుతోంది. మీరు సెటప్ కొనసాగించవచ్చు.",
            onboardingPadWaitingHint = "బ్రెయిన్ డౌన్‌లోడ్ ప్రారంభించడానికి నెట్‌వర్క్ అనుమతి/కనెక్షన్ కోసం వేచి చూస్తున్నాం. మీరు సెటప్ కొనసాగించవచ్చు.",
            micMainContentDescription = "మాట్లాడండి — మీ భాషలో వింటుంది; సమాధానాలు మీ భాషలో.",
            chatToolbarSwitchToTypeLabel = "కీబోర్డ్‌తో రాయండి",
            chatToolbarSwitchToVoiceLabel = "వాయిస్ సంభాషణకు మారండి",
            chatToolbarClearLabel = "చాట్ తుడిచివేయి",
            chatToolbarSettingsLabel = "సెట్టింగ్‌లు",
            chatToolbarFeedbackLabel = "అభిప్రాయం పంపండి",
            brainNetworkHeadline = "మీ GyanGo దాదాపు సిద్ధంగా ఉంది",
            brainNetworkSubtext = "మీరు ఇప్పుడు Wi‑Fi లో ఉన్నారు. మృదువైన అనుభవం కోసం అవసరమైనదంతా ఇప్పుడే డౌన్‌లోడ్ చేసుకోవచ్చు.",
            brainNetworkWifiOnly = "నేను Wi‑Fiలో ఉన్నప్పుడు కొనసాగించు",
            brainNetworkProceedNow = "ఇప్పుడే మొదలుపెట్టు",
            brainWaitingWifiHeadline = "Wi‑Fi కోసం వేచి ఉన్నాం",
            brainWaitingWifiSubtext = "Wi‑Fi స్థిరమైన డౌన్‌లోడ్‌కు మంచిది. కనెక్ట్ అయ్యాక డౌన్‌లోడ్ స్వయంచాలకంగా మొదలవుతుంది; కింద ఎంపికలతో మీరు మార్చుకోవచ్చు.",
            brainWaitingWifiOptionsTitle = "ఎంపికలు",
            brainWaitingWifiContinueDownloadButton = "ఇప్పుడే కొనసాగించు",
            brainWaitingWifiResumeLaterButton = "తర్వాత కొనసాగిస్తాను",
            brainPreparingHeadline = "మీ ఫోన్‌కు “బ్రెయిన్” సిద్ధమవుతోంది",
            brainPreparingSubtext = "ఒక్కసారి పూర్తయ్యే బదిలీ — దయచేసి ఈ స్క్రీన్‌ను మూసివేయకండి.",
            brainMergingDetail = "భాగాలను కలుపుతున్నాం…",
            brainRetryDownloadButton = "మళ్లీ ప్రయత్నించండి",
            brainDownloadFailedHeadline = "డౌన్‌లోడ్ పూర్తి కాలేదు",
            onboardingIntroTitle = "GyanGo కి స్వాగతం",
            onboardingIntroBody = "పూర్తిగా మీ ఫోన్‌లోనే పనిచేస్తుంది — ఎయిర్‌ప్లేన్ మోడ్‌లో కూడా. మీ చాట్ మీ పరికరాన్ని విడిచిపోదు.",
            onboardingIntroContinue = "మొదలుపెడదాం",
            onboardingWelcomeTitle = "GyanGo కి స్వాగతం",
            onboardingWelcomeBody = "మనం ఒకరినొకరం బాగా తెలుసుకుందాం. మీ పేరు, మీరు మాట్లాడే భాష చెప్పండి.",
            onboardingFirstNameLabel = "మొదటి పేరు",
            onboardingLastNameLabel = "ఇంటి పేరు / చివరి పేరు",
            onboardingBirthOptionalSection = "పుట్టిన తేదీ (ఐచ్చికం)",
            onboardingBirthMonthLabel = "నెల",
            onboardingBirthMonthNotSet = "ఇవ్వలేదు",
            onboardingBirthYearLabel = "సంవత్సరం",
            onboardingLanguageSection = "భాష",
            onboardingVoiceSection = "స్వరం",
            onboardingReadAloudSection = "సమాధానాలు విని నేర్చుకోవాలా?",
            onboardingReadAloudNoLabel = "వద్దు",
            onboardingReadAloudYesLabel = "అవును",
            onboardingContinue = "కొనసాగించు",
            ttsSetupTitle = "వాయిస్ ప్యాక్ అవసరం",
            ttsSetupBody = "ఈ భాషలో సమాధానాలు వినాలంటే Android speech package డౌన్‌లోడ్ చేయాలి. కొనసాగించగానే Android సెట్టింగ్ తెరుచుకుంటుంది.",
            ttsSetupInstallButton = "Android లో ప్యాక్ డౌన్‌లోడ్ చేయి",
            ttsSetupSkipButton = "ఇప్పుడే వద్దు",
            onboardingHardwareUnsupportedTitle = "ఈ ఫోన్‌లో ఈ మోడల్ నడవదు",
            onboardingHardwareUnsupportedBody =
                "GyanGo కి సమర్థ GPU లేదా NPU మరియు కనీసం 6 GB సిస్టమ్ మెమరీ అవసరం. ఈ పరికరం ఆ అవసరాలను తీర్చదు.",
            onboardingHardwareUnsupportedPerformanceNote =
                "ఈ మోడల్ సుమారు 2.3 GB — తక్కువ RAM లేదా CPU‑మాత్రమే మార్గంలో అది నెమ్మదిగా ఉంటుంది లేదా స్థిరంగా నడవకపోవచ్చు. సాధారణ వేగానికి సమర్థ GPU లేదా NPU మరియు 6 GB కంటే ఎక్కువ RAM ఉన్న ఫోన్ వాడండి.",
            settingsTitle = "సెట్టింగ్‌లు",
            settingsConversationLanguage = "సంభాషణ భాష",
            settingsConversationLanguageHint = "సహాయక సమాధానాల భాష, ఈ స్క్రీన్‌పై టెక్స్ట్, మరియు వాయిస్ ఇన్‌పుట్. మార్పు తర్వాత కొత్త సందేశాలకు వర్తిస్తుంది.",
            settingsSpeechPickerTitle = "సంభాషణ భాష",
            settingsApply = "వర్తింపజేయి",
            settingsCancel = "రద్దు",
            settingsHubTitle = "సెట్టింగ్‌లు",
            settingsHubProfileTitle = "వినియోగదారు ప్రొఫైల్",
            settingsHubProfileSubtitle = "పేరు, ఇమెయిల్, పుట్టిన తేదీ, భాష, చదవడం",
            settingsHubChatTitle = "చాట్ & మోడల్",
            settingsHubChatSubtitle = "సమాధాన పొడవు, ఆలోచన సూచనలు, సృజనాత్మకత",
            settingsProfileTitle = "వినియోగదారు ప్రొఫైల్",
            settingsChatTitle = "చాట్ & మోడల్",
            settingsBack = "వెనక్కి",
            settingsClose = "మూసివేయి",
            profileEmailLabel = "ఇమెయిల్ (ఐచ్చికం)",
            settingsBirthAgeHint = "వయస్సు-సరిపోయే సమాధానాలు మరియు భద్రత కోసం మాత్రమే ఉపయోగిస్తాం.",
            settingsChatLongAnswersTitle = "పొడవైన సమాధానాలు కావాలా?",
            settingsChatLongAnswersHint = "ఆన్ అయితే సమాధానాలు కొంచెం పొడవుగా ఉండవచ్చు. ఆఫ్ అయితే త్వరగా, చిన్నగా ఉంచడానికి ప్రయత్నిస్తాం.",
            settingsChatReasoningTitle = "మోడల్ ఆలోచన ప్రక్రియ చూపించాలా?",
            settingsChatReasoningHint = "ఆన్ అయితే సహాయకుడు లోపలి తర్కాన్ని సంక్షిప్తంగా గుర్తుచేస్తాడు. చాలా పరికరాలలో ఇది కొంచెం ఎక్కువ సమయం తీసుకోవచ్చు.",
            settingsChatCreativityTitle = "సమాధానాలు ఎంత సృజనాత్మకంగా ఉండాలి?",
            settingsChatCreativityHint = "తక్కువ వద్ద స్థిరంగా ఉంటుంది; ఎక్కువ వద్ద మరింత భిన్నమైన పదాలు రావచ్చు.",
            settingsChatLowPowerTitle = "బ్యాటరీని కాపాడటం (త్వరలో)",
            settingsChatLowPowerHint = "ఇప్పటికి ప్రభావం లేదు; రాబోయే వెర్షన్‌లలో వేగం మరియు శక్తిని సమతుల్యం చేయడానికి ఉపయోగిస్తాం.",
            settingsChangeConversationLanguage = "భాష మార్చు",
            settingsHubInterestsTitle = "మీ ఆసక్తులు",
            settingsHubInterestsSubtitle = "GyanGo గమనించిన థీమ్‌లు — డేటా ఈ ఫోన్‌లోనే ఉంటుంది",
            settingsAboutTitle = "గురించి",
            settingsVersionFormat = "వెర్షన్ %1\$s (%2\$s)",
            settingsInterestsTitle = "ఆసక్తి నోట్‌లు",
            settingsInterestsEmpty = "ఇంకా ఏమీ లేదు. కొన్ని సమాధానాల తర్వాత GyanGo ఒక చిన్న ఇంటరెస్ట్ ట్యాగ్‌ను జోడించవచ్చు; లేకపోయినా సరే.",
            settingsInterestsHint = "మీ సంభాషణా భాషలోనే ఉంటాయి. ఇవి మోడల్‌కు తిరిగి పంపబడవు. క్లియర్‌తో ఇక్కడి జాబితా తుడిచివేయండి.",
            settingsInterestsClearButton = "అన్నింటిని తొలగించు",
            settingsInterestsDoneButton = "పూర్తయింది",
            settingsInterestsTopicPrefix = "విషయం",
            settingsInterestsQuestionPrefix = "మీ ప్రశ్న",
            onboardingHardwareChecklistTitle = "ఏమి సరిపోలేదో",
            onboardingHardwareNoAccelCard = "సపోర్ట్ GPU లేదా NPU లేదు — మా మోడల్ ఇక్కడ వేగంగా నడవదు.",
            onboardingHardwareLowRamCard = "మొత్తం RAM సుమారు 6 GB కంటే తక్కువ — ఈ పరిమాణ మోడల్‌కు సరిపోదు.",
            onboardingHardwareLowDiskCard = "ఖాళీ స్టోరేజ్ తక్కువ — ఇన్‌స్టాల్/మెర్జ్‌కు కనీసం ~3.5 GB ఖాళీ కావాలి.",
            childSafeBanner = "పిల్లల కోసం సురక్షిత మోడ్ ఆన్‌లో ఉంది",
        )
        localeTag.startsWith("hi", ignoreCase = true) -> ChatDisplayStrings(
            topBarTitle = CHAT_ASSISTANT_DISPLAY_NAME,
            topBarCaption = CHAT_BRAND_TAGLINE,
            emptyVoicePrimaryTitle = "आवाज़ से शुरुआत करें",
            emptyVoicePrimarySubtitle = "माइक्रोफ़ोन पर टैप करें और स्वाभाविक रूप से बोलें — $ASSISTANT इसी फ़ोन पर सुनता और जवाब देता है।",
            emptyTextModeTitle = "लेखन से शुरुआत करें",
            emptyTextModeSubtitle = "संदेश टाइप करें, या छवि जोड़ें ताकि उस पर लिखा टेक्स्ट शामिल हो (OCR)। ज़रूरत हो तो टूलबार से आवाज़ मोड पर जाएँ।",
            loadingModelMessage = "मॉडल तैयार हो रहा है — एक पल।",
            assistantJsonStreamingPlaceholder = "सोच रहा हूँ…",
            assistantAwaitingStreamHints = listOf(
                "आपका सवाल इसी फ़ोन पर रहता है — जवाब तैयार कर रहे हैं…",
                "बिना क्लाउंड राउंड‑ट्रिप के — यहीं पर सोच रहे हैं…",
                "साफ़, छोटे बिंदुओं में समेट रहे हैं…",
                "पढ़ने में आसान बनाने में एक पल…",
                "पहले शब्द जल्द ही…",
            ),
            loadingDeviceModelTitle = "ऑन‑डिवाइस AI तैयार हो रहा है",
            loadingDeviceModelSubtitle = "पहली बार थोड़ा समय लग सकता है। कृपया प्रतीक्षा करें।",
            modelLoadFailedTitle = "मॉडल लोड नहीं हो सका",
            modelLoadRetryButton = "फिर कोशिश करें",
            onboardingProgressSavedHint = "आपकी जानकारी इस डिवाइस पर सहेजी जाती है।",
            onboardingPadDownloadingHint = "ब्रेन मॉडल बैकग्राउंड में डाउनलोड हो रहा है। आप सेटअप जारी रख सकते हैं।",
            onboardingPadWaitingHint = "ब्रेन डाउनलोड शुरू करने के लिए नेटवर्क अनुमति/कनेक्शन का इंतज़ार है। आप सेटअप जारी रख सकते हैं।",
            micMainContentDescription = "बोलें — आपकी भाषा में सुनेगा; जवाब उसी भाषा में।",
            chatToolbarSwitchToTypeLabel = "कीबोर्ड से लिखें",
            chatToolbarSwitchToVoiceLabel = "आवाज़ वार्ता पर जाएँ",
            chatToolbarClearLabel = "चैट साफ़ करें",
            chatToolbarSettingsLabel = "सेटिंग्स",
            chatToolbarFeedbackLabel = "फ़ीडबैक भेजें",
            brainNetworkHeadline = "आपका GyanGo लगभग तैयार है",
            brainNetworkSubtext = "आप Wi‑Fi पर हैं, इसलिए अभी सब कुछ डाउनलोड कर लेना बेहतर रहेगा ताकि अनुभव और सहज रहे।",
            brainNetworkWifiOnly = "Wi‑Fi मिलने पर जारी रखें",
            brainNetworkProceedNow = "शुरू करें",
            brainWaitingWifiHeadline = "Wi‑Fi की प्रतीक्षा",
            brainWaitingWifiSubtext = "Wi‑Fi स्थिर डाउनलोड के लिए बेहतर है। जुड़ते ही डाउनलोड अपने आप शुरू होगा; नीचे से आप बदल सकते हैं।",
            brainWaitingWifiOptionsTitle = "विकल्प",
            brainWaitingWifiContinueDownloadButton = "अभी जारी रखें",
            brainWaitingWifiResumeLaterButton = "बाद में जारी रखूँगा/रखूँगी",
            brainPreparingHeadline = "आपके फ़ोन के लिए “ब्रेन” तैयार हो रहा है",
            brainPreparingSubtext = "यह एक बार का स्थानांतरण है — कृपया इस स्क्रीन को बंद न करें।",
            brainMergingDetail = "खंड जोड़े जा रहे हैं…",
            brainRetryDownloadButton = "फिर कोशिश करें",
            brainDownloadFailedHeadline = "डाउनलोड पूरा नहीं हुआ",
            onboardingIntroTitle = "GyanGo में आपका स्वागत है",
            onboardingIntroBody = "यह पूरी तरह आपके फ़ोन पर चलता है — एयरप्लेन मोड में भी। आपकी चैट आपके डिवाइस से बाहर नहीं जाती।",
            onboardingIntroContinue = "शुरू करें",
            onboardingWelcomeTitle = "GyanGo में आपका स्वागत है",
            onboardingWelcomeBody = "थोड़ा सा अपने बारे में बताइए — आपका नाम और आप किस भाषा में बात करना चाहते हैं।",
            onboardingFirstNameLabel = "पहला नाम",
            onboardingLastNameLabel = "अंतिम नाम",
            onboardingBirthOptionalSection = "जन्म तिथि (वैकल्पिक)",
            onboardingBirthMonthLabel = "महीना",
            onboardingBirthMonthNotSet = "नहीं चुनें",
            onboardingBirthYearLabel = "वर्ष",
            onboardingLanguageSection = "भाषा",
            onboardingVoiceSection = "आवाज़",
            onboardingReadAloudSection = "क्या जवाब सुनकर सीखना है?",
            onboardingReadAloudNoLabel = "नहीं",
            onboardingReadAloudYesLabel = "हाँ",
            onboardingContinue = "आगे बढ़ें",
            ttsSetupTitle = "वॉइस पैक चाहिए",
            ttsSetupBody = "इस भाषा में जवाब सुनने के लिए Android speech package डाउनलोड करना होगा। जारी रखने पर Android सेटिंग खुलेगी।",
            ttsSetupInstallButton = "Android में पैक डाउनलोड करें",
            ttsSetupSkipButton = "अभी नहीं",
            onboardingHardwareUnsupportedTitle = "यह फ़ोन मॉडल नहीं चला सकता",
            onboardingHardwareUnsupportedBody =
                "GyanGo के लिए एक समर्थ GPU या NPU और कम से कम 6 GB सिस्टम मेमोरी ज़रूरी है। यह डिवाइस इन ज़रूरतों को पूरा नहीं करता।",
            onboardingHardwareUnsupportedPerformanceNote =
                "यह मॉडल लगभग 2.3 GB का है — कम RAM या केवल‑CPU चलाने पर जवाब बहुत धीमे हो सकते हैं या स्थिर नहीं रह सकता। सामान्य अनुभव के लिए उपयुक्त GPU या NPU और 6 GB से ज़्यादा RAM वाला फ़ोन चुनें।",
            settingsTitle = "सेटिंग्स",
            settingsConversationLanguage = "बातचीत की भाषा",
            settingsConversationLanguageHint = "सहायक के जवाबों की भाषा, इस स्क्रीन का टेक्स्ट, और आवाज़ इनपुट। बदलाव के बाद के नए संदेशों पर लागू होता है।",
            settingsSpeechPickerTitle = "बातचीत की भाषा",
            settingsApply = "लागू करें",
            settingsCancel = "रद्द करें",
            settingsHubTitle = "सेटिंग्स",
            settingsHubProfileTitle = "उपयोगकर्ता प्रोफ़ाइल",
            settingsHubProfileSubtitle = "नाम, ईमेल, जन्म तिथि, भाषा, ज़ोर से पढ़ना",
            settingsHubChatTitle = "चैट और मॉडल",
            settingsHubChatSubtitle = "जवाब की लंबाई, सोच के संकेत, रचनात्मकता",
            settingsProfileTitle = "उपयोगकर्ता प्रोफ़ाइल",
            settingsChatTitle = "चैट और मॉडल",
            settingsBack = "पीछे",
            settingsClose = "बंद करें",
            profileEmailLabel = "ईमेल (वैकल्पिक)",
            settingsBirthAgeHint = "केवल उम्र के अनुकूल और सुरक्षित जवाबों के लिए उपयोग होता है।",
            settingsChatLongAnswersTitle = "क्या ज़्यादा लंबे जवाब चाहिए?",
            settingsChatLongAnswersHint = "चालू करने पर जवाब थोड़े लंबे हो सकते हैं। बंद करने पर हम जल्दी और छोटे जवाबों की कोशिश करते हैं।",
            settingsChatReasoningTitle = "क्या मॉडल की सोच की प्रक्रिया दिखाएँ?",
            settingsChatReasoningHint = "चालू करने पर सहायक अंदरूनी तर्क को संक्षेप में याद दिलाता है। कई फ़ोनों पर इसमें थोड़ा ज़्यादा समय लग सकता है।",
            settingsChatCreativityTitle = "जवाब कितने रचनात्मक हों?",
            settingsChatCreativityHint = "कम पर अधिक स्थिर; ज़्यादा पर शब्द थोड़े अलग-अलग आ सकते हैं।",
            settingsChatLowPowerTitle = "बैटरी बचाएँ (जल्द आ रहा है)",
            settingsChatLowPowerHint = "अभी कोई असर नहीं; आने वाले वर्ज़न में गति और बैटरी संतुलन के लिए।",
            settingsChangeConversationLanguage = "भाषा बदलें",
            settingsHubInterestsTitle = "आपकी रुचियाँ",
            settingsHubInterestsSubtitle = "GyanGo ने जो थीम देखीं — डेटा सिर्फ़ इस फ़ोन पर",
            settingsAboutTitle = "ऐप के बारे में",
            settingsVersionFormat = "संस्करण %1\$s (%2\$s)",
            settingsInterestsTitle = "रुचि नोट्स",
            settingsInterestsEmpty = "अभी कुछ नहीं। कुछ जवाबों के बाद GyanGo छोटा इंटरेस्ट टैग जोड़ सकता है; न हो तो भी ठीक है।",
            settingsInterestsHint = "आपकी चुनी भाषा में रहते हैं; मॉडल को वापस नहीं भेजे जाते। साफ़ करने से यहाँ की सूची मिट जाएगी।",
            settingsInterestsClearButton = "सब हटाएँ",
            settingsInterestsDoneButton = "हो गया",
            settingsInterestsTopicPrefix = "विषय",
            settingsInterestsQuestionPrefix = "आपका सवाल",
            onboardingHardwareChecklistTitle = "क्या पूरा नहीं हुआ",
            onboardingHardwareNoAccelCard = "समर्थ GPU या NPU नहीं — यहाँ ऑन‑डिवाइस मॉडल तेज़ नहीं चल सकता।",
            onboardingHardwareLowRamCard = "कुल RAM लगभग 6 GB से कम — इस मॉडल साइज़ के लिए पर्याप्त नहीं।",
            onboardingHardwareLowDiskCard = "खाली स्टोरेज कम है — इंस्टॉल/मर्ज के लिए लगभग 3.5 GB खाली जगह चाहिए।",
            childSafeBanner = "बच्चों के लिए सुरक्षित मोड चालू है",
        )
        else -> ChatDisplayStrings(
            topBarTitle = CHAT_ASSISTANT_DISPLAY_NAME,
            topBarCaption = CHAT_BRAND_TAGLINE,
            emptyVoicePrimaryTitle = "Start with your voice",
            emptyVoicePrimarySubtitle = "Tap the microphone and speak naturally — $ASSISTANT listens and replies entirely on this device.",
            emptyTextModeTitle = "Start in writing",
            emptyTextModeSubtitle = "Type a message, or attach an image to include the text on it (OCR). Switch to voice anytime from the toolbar.",
            loadingModelMessage = "Getting the model ready — one moment.",
            assistantJsonStreamingPlaceholder = "Thinking…",
            assistantAwaitingStreamHints = listOf(
                "GyanGo is lining this up entirely on your device — hang tight…",
                "No cloud round-trip; your question stays on this phone while I think…",
                "Taking a careful pass so the answer is easy to skim…",
                "Still streaming — good reasoning is worth a short pause…",
                "First tokens are almost here…",
            ),
            loadingDeviceModelTitle = "Preparing on-device AI",
            loadingDeviceModelSubtitle = "The first launch can take a moment. Please stay on this screen.",
            modelLoadFailedTitle = "Could not load the model",
            modelLoadRetryButton = "Try again",
            onboardingProgressSavedHint = "Your details are saved on this device as you type.",
            onboardingPadDownloadingHint = "Brain model download is running in the background. You can continue setup.",
            onboardingPadWaitingHint = "Waiting for network permission/connection to start the brain download. You can continue setup.",
            micMainContentDescription = "Speak — listens in your chosen language; replies in that language.",
            chatToolbarSwitchToTypeLabel = "Compose with keyboard",
            chatToolbarSwitchToVoiceLabel = "Speak with GyanGo",
            chatToolbarClearLabel = "Clear conversation",
            chatToolbarSettingsLabel = "Settings",
            chatToolbarFeedbackLabel = "Send feedback",
            brainNetworkHeadline = "Your GyanGo is almost ready",
            brainNetworkSubtext = "You're on Wi-Fi, so this is a good time to download everything for a smoother experience.",
            brainNetworkWifiOnly = "Continue when I'm on Wi‑Fi",
            brainNetworkProceedNow = "Go for it",
            brainWaitingWifiHeadline = "Waiting for Wi‑Fi",
            brainWaitingWifiSubtext = "Wi‑Fi is best for a stable download. We'll start automatically when this phone connects, or you can choose below.",
            brainWaitingWifiOptionsTitle = "Options",
            brainWaitingWifiContinueDownloadButton = "Go for it",
            brainWaitingWifiResumeLaterButton = "Resume download later",
            brainPreparingHeadline = "Preparing the on-device model",
            brainPreparingSubtext = "One-time setup — please keep this screen open until we finish.",
            brainMergingDetail = "Assembling model parts…",
            brainRetryDownloadButton = "Try again",
            brainDownloadFailedHeadline = "Download could not finish",
            onboardingIntroTitle = "Welcome to GyanGo",
            onboardingIntroBody = "Your phone. Your AI. Your privacy.",
            onboardingIntroContinue = "Let’s get started",
            onboardingWelcomeTitle = "Welcome to GyanGo",
            onboardingWelcomeBody = "Tell me about yourself, your language, and what you'd like to chat in.",
            onboardingFirstNameLabel = "First name",
            onboardingLastNameLabel = "Last name",
            onboardingBirthOptionalSection = "Birth date (optional)",
            onboardingBirthMonthLabel = "Month",
            onboardingBirthMonthNotSet = "Not set",
            onboardingBirthYearLabel = "Year",
            onboardingLanguageSection = "Language",
            onboardingVoiceSection = "Voice",
            onboardingReadAloudSection = "Read answers aloud?",
            onboardingReadAloudNoLabel = "No",
            onboardingReadAloudYesLabel = "Yes",
            onboardingContinue = "Continue",
            ttsSetupTitle = "Voice package needed",
            ttsSetupBody = "To read answers aloud in this language, Android needs a speech package download. Continue to open Android setup.",
            ttsSetupInstallButton = "Download in Android setup",
            ttsSetupSkipButton = "Not now",
            onboardingHardwareUnsupportedTitle = "This phone cannot run the model",
            onboardingHardwareUnsupportedBody =
                "GyanGo needs a supported GPU or NPU and at least 6 GB of system memory. This device does not meet those requirements.",
            onboardingHardwareUnsupportedPerformanceNote =
                "The on-device model is about 2.3 GB. On low RAM or a CPU-only path it would be too slow or unstable for chat. Use a phone with a capable GPU or NPU and more than 6 GB RAM for a smooth experience.",
            settingsTitle = "Settings",
            settingsConversationLanguage = "Conversation language",
            settingsConversationLanguageHint = "Language for assistant replies, on-screen chat text, and voice input. Applies to new messages after you change it.",
            settingsSpeechPickerTitle = "Conversation language",
            settingsApply = "Apply",
            settingsCancel = "Cancel",
            settingsHubTitle = "Settings",
            settingsHubProfileTitle = "User profile",
            settingsHubProfileSubtitle = "Name, email, birth date, language, read-aloud",
            settingsHubChatTitle = "Chat & model",
            settingsHubChatSubtitle = "Reply length, thinking hints, creativity",
            settingsProfileTitle = "User profile",
            settingsChatTitle = "Chat & model",
            settingsBack = "Back",
            settingsClose = "Close",
            profileEmailLabel = "Email (optional)",
            settingsBirthAgeHint = "Used only to keep replies age-appropriate and safety-aware.",
            settingsChatLongAnswersTitle = "Longer answers?",
            settingsChatLongAnswersHint = "When on, replies can run longer. When off, we aim for quicker, shorter answers.",
            settingsChatReasoningTitle = "Show the model’s thinking process?",
            settingsChatReasoningHint = "When on, the assistant adds a short private reasoning reminder. This can add a little time on some phones.",
            settingsChatCreativityTitle = "How creative should answers be?",
            settingsChatCreativityHint = "Lower stays steadier; higher allows more varied wording.",
            settingsChatLowPowerTitle = "Save battery (coming soon)",
            settingsChatLowPowerHint = "No effect yet; reserved for a future speed vs battery balance.",
            settingsChangeConversationLanguage = "Change language",
            settingsHubInterestsTitle = "Your interests",
            settingsHubInterestsSubtitle = "Themes GyanGo noticed — stored only on this phone",
            settingsAboutTitle = "About",
            settingsVersionFormat = "Version %1\$s (%2\$s)",
            settingsInterestsTitle = "Interest notes",
            settingsInterestsEmpty = "Nothing here yet. After some replies, GyanGo may add a small optional interest tag; if it doesn’t, that’s fine.",
            settingsInterestsHint = "These stay in your conversation language and are not sent back into the model. Clear removes the list on this device.",
            settingsInterestsClearButton = "Clear all",
            settingsInterestsDoneButton = "Done",
            settingsInterestsTopicPrefix = "Topic",
            settingsInterestsQuestionPrefix = "Your question",
            onboardingHardwareChecklistTitle = "What didn’t pass the check",
            onboardingHardwareNoAccelCard = "No supported GPU or NPU — the on-device model can’t run fast enough on this phone.",
            onboardingHardwareLowRamCard = "Total memory is under about 6 GB — not enough headroom for this model size.",
            onboardingHardwareLowDiskCard = "Free storage is low — we need roughly 3.5 GB free for a safe install or update.",
            childSafeBanner = "Kids-safe mode is on",
        )
    }
}

@Composable
fun rememberChatDisplayStrings(localeTag: String): ChatDisplayStrings =
    remember(localeTag) { chatDisplayStringsForLocale(localeTag) }
